### ISSUE TITLE
ImportError: No module named wrapper_util

### ISSUE THREAD

**Issue by mhsn06** [potatolondon/djangae-scaffold#106]
while running the command
"python manage.py runserver" the following error is raised.

ImportError: No module named wrapper_util

**Comment by davidwtbuxton** [comment]
Hi,

Could you give some more detail please? Do you have a full stack trace? What versions of Django / Djangae / the SDK are you using? What is the value of `sys.path` at the point in the code where the exception is raised?

Thanks,

David B.

**Comment by MitchSRobinson** [comment]
Hi there @davidwtbuxton,

I'm having a similar problem (very new to djangae so I'm sure it's a simple fix but I can't figure it out).

Getting `ImportError: No module named wrapper_util` when trying to run `python manage.py collectstatic`.

Stack trace:
`Traceback (most recent call last):
  File "manage.py", line 18, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Python27\lib\site-packages\djangae\core\management\__init__.py", line 43, in execute_from_command_line
    return _execute_from_command_line(djangae_namespace.sandbox, argv, parser=djangae_parser, **overrides)
  File "C:\Python27\lib\site-packages\djangae\core\management\__init__.py", line 64, in _execute_from_command_line
    **sandbox_overrides
  File "C:\Python27\lib\contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "C:\Python27\lib\site-packages\djangae\sandbox.py", line 448, in activate
    import wrapper_util
ImportError: No module named wrapper_util`

Django: 1.11
GCloud Version: 162.0.0
Djangae: 0.9.11-alpha

Main issue I'm trying to solve is that `dev_appserver.py app.yaml` creates a dev server but there doesn't seem to be any static files - 404 for base and dashboard.css for the admin panel

Thanks,
Mitch
