### ISSUE TITLE
ImportError: No module named mapreduce.mapper_pipeline

### ISSUE THREAD

**Issue by slumtrimpet** [potatolondon/djangae-scaffold#50]
Following the install docs, error on step three:

```
python manage.py checksecure --settings=portal.settings_live
```

```
WARNING  2015-07-22 20:48:06,376 simple_search_stub.py:1126] Could not read search indexes from /apps/djangae-scaffold/.storage/search_indexes
INFO     2015-07-22 20:48:06,484 blobstore_service.py:57] Starting blobstore service on localhost:8080
Traceback (most recent call last):
  File "manage.py", line 13, in <module>
    execute_from_command_line(sys.argv)
  File "/apps/djangae-scaffold/sitepackages/djangae/core/management/__init__.py", line 56, in execute_from_command_line
    return _execute_from_command_line(namespace.sandbox, ['manage.py'] + namespace.args, **overrides)
  File "/apps/djangae-scaffold/sitepackages/djangae/core/management/__init__.py", line 36, in _execute_from_command_line
    return django_management.execute_from_command_line(argv)
  File "/apps/djangae-scaffold/sitepackages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/apps/djangae-scaffold/sitepackages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/apps/djangae-scaffold/sitepackages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/apps/djangae-scaffold/sitepackages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/apps/djangae-scaffold/sitepackages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/apps/djangae-scaffold/sitepackages/djangae/contrib/uniquetool/models.py", line 14, in <module>
    from djangae.contrib.mappers.pipes import MapReduceTask, DjangaeMapperPipeline, PIPELINE_BASE_PATH
  File "/apps/djangae-scaffold/sitepackages/djangae/contrib/mappers/pipes.py", line 1, in <module>
    from mapreduce.mapper_pipeline import MapperPipeline
ImportError: No module named mapreduce.mapper_pipeline
```

**Comment by adamalton** [comment]
Ah yeah, you can either remove 'djangae.contrib.uniquetool' from INSTALLED_APPS or un-comment the mapreduce libraries in requirements.txt.

Leaving this open as we should do one or the other of those as the default.

**Comment by adamalton** [comment]
I've now changed `INSTALLED_APPS` so that `'djangae.contrib.uniquetool'` is not included by default.
