### ISSUE TITLE
Problem running the example

### ISSUE THREAD

**Issue by andretietz** [potatolondon/djangae-scaffold#61]
When I am executing

    python manage.py checksecure --settings=scaffold.settings_live

I get an error. Here the full stacktrace:

    INFO     2015-12-10 16:40:53,200 blobstore_service.py:70] Starting blobstore service on localhost:8080
		Traceback (most recent call last):
		File "manage.py", line 13, in <module>
    execute_from_command_line(sys.argv)
		File "/Users/a.tietz/djangogae/djangae-scaffold/sitepackages/djangae/core/management/__init__.py", line 65, in execute_from_command_line
		return _execute_from_command_line(namespace.sandbox, ['manage.py'] + namespace.args, **overrides)
		File "/Users/a.tietz/djangogae/djangae-scaffold/sitepackages/djangae/core/management/__init__.py", line 45, in _execute_from_command_line
		return django_management.execute_from_command_line(argv)
		File "/Users/a.tietz/djangogae/djangae-scaffold/sitepackages/django/core/management/__init__.py", line 354, in execute_from_command_line
		utility.execute()
		File "/Users/a.tietz/djangogae/djangae-scaffold/sitepackages/django/core/management/__init__.py", line 303, in execute
		settings.INSTALLED_APPS
		File "/Users/a.tietz/djangogae/djangae-scaffold/sitepackages/django/conf/__init__.py", line 48, in __getattr__
		self._setup(name)
		File "/Users/a.tietz/djangogae/djangae-scaffold/sitepackages/django/conf/__init__.py", line 44, in _setup
		self._wrapped = Settings(settings_module)
		File "/Users/a.tietz/djangogae/djangae-scaffold/sitepackages/django/conf/__init__.py", line 92, in __init__
		mod = importlib.import_module(self.SETTINGS_MODULE)
		File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
		__import__(name)
		ImportError: No module named scaffold.settings_live

Any clue what I do wrong there?

It's running on Django 1.8.7 everything else comes with your project (thx btw for this!)

**Comment by moggers87** [comment]
Runs fine for me.

Did you run `rename_scaffold_app`? If so, then you need to do `python manage.py checksecure --settings=<new app name>.settings_live` instead.

**Comment by andretietz** [comment]
Sorry, my bet, you're right!
