### ISSUE TITLE
ImportError: No module named importlib

### ISSUE THREAD

**Issue by iqqmuT** [potatolondon/djangae-scaffold#75]
When I tried to run `python manage.py checksecure --settings=myapp.settings_live` I got the following error:
```
WARNING  2016-03-24 15:37:02,269 simple_search_stub.py:1126] Could not read search indexes from /home/user/projects/myapp/djangae-scaffold/.storage/search_indexes
INFO     2016-03-24 15:37:02,287 blobstore_service.py:73] Starting blobstore service on localhost:8080
WARNING  2016-03-24 15:37:02,287 blobstore_service.py:77] Not starting blobstore service, it may already be running
Traceback (most recent call last):
  File "manage.py", line 13, in <module>
    execute_from_command_line(sys.argv)
  File "/home/user/projects/myapp/djangae-scaffold/sitepackages/djangae/core/management/__init__.py", line 65, in execute_from_command_line
    return _execute_from_command_line(namespace.sandbox, ['manage.py'] + namespace.args, **overrides)
  File "/home/user/projects/myapp/djangae-scaffold/sitepackages/djangae/core/management/__init__.py", line 45, in _execute_from_command_line
    return django_management.execute_from_command_line(argv)
  File "/home/user/projects/myapp/djangae-scaffold/sitepackages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/user/projects/myapp/djangae-scaffold/sitepackages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/user/projects/myapp/djangae-scaffold/sitepackages/django/core/management/__init__.py", line 195, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/home/user/projects/myapp/djangae-scaffold/sitepackages/django/core/management/__init__.py", line 39, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/projects/myapp/djangae-scaffold/sitepackages/djangosecure/management/commands/checksecure.py", line 6, in <module>
    from ...check import get_check
  File "/home/user/projects/myapp/djangae-scaffold/sitepackages/djangosecure/check/__init__.py", line 1, in <module>
    from .run import get_check, run_checks
  File "/home/user/projects/myapp/djangae-scaffold/sitepackages/djangosecure/check/run.py", line 1, in <module>
    from django.utils.importlib import import_module
ImportError: No module named importlib
```

Apparently Django 1.9 is not supported?

**Comment by olasitarska** [comment]
Hi @iqqmuT! Thanks for reporting this issue. Djangae supports Django 1.9, but apparently django-secure (which is installed in default with djangae-scaffold) does not support Django 1.9. I created #76, we will fix it whenever we got a chance, but pull request are very welcome too :)
